### ISSUE TITLE
Pressing escape button must zoom out the view

### ISSUE THREAD

**Issue by gautamkrishnar** [zircleUI/github-trending-plus#1]
The user must be able to zoom out using escape button.

**Comment by tinchox5** [comment]
Thanks! I’ll work on that

**Comment by tinchox5** [comment]
@gautamkrishnar I added the feature you suggest. It should be working online. Thanks!

**Comment by gautamkrishnar** [comment]
Cool 🎉 Working perfectly...

**Comment by tinchox5** [comment]
Good to hear that!! Alternatively you can go back using scroll and mouse wheel on desktops and swipe up on mobile
