### ISSUE TITLE
Vercel Deployment Hosting GitHub Trending API Disabled, Breaking Example in ZircleUI Documentation

### ISSUE THREAD

**Issue by binlabs** [zircleUI/github-trending-plus#25]
I had a hard time deciding where to open this bug.

The bug can be seen from the [demo URL in the README](https://github-trending-api.vercel.app/) of this repository and from the [GitHub Trending Plus page](https://zircleui.github.io/docs/examples/github-trending-plus.html) of the [ZircleUI Documentation site](https://zircleui.github.io/docs/examples/github-trending-plus.html), but I believe the example being embedded there is a deployment on behalf of this repository. If I'm wrong, let me know and I can open this issue in the ZircleUI/Docs or wherever is more appropriate.

The GitHub Trending Plus example in the docs make requests for GitHub data to these two endpoints:
https://github-trending-api.now.sh/repositories?since=daily&language=
https://github-trending-api.now.sh/developers?since=daily&language=

Those two requests get 308 redirected to these two endpoints respectively:
https://github-trending-api.vercel.app/repositories?since=daily&language=
https://github-trending-api.vercel.app/developers?since=daily&language=

Both of those requests to the Vercel deployment return a 451 error, and viewing them in the browser you can see that Vercel is saying the deployment has been disabled.

Due to those 451 errors, the example is not working as intended, and clicking on the "top repos" or "top devs" results in the display of text saying "Oops!! Network Error" above an infinite loading spinner.

I'd personally love to see this example working again if isn't too much trouble to get a deployment of the GitHub Trending API spun up again.

**Comment by tinchox5** [comment]
Sorry, I'll fix that. We are releasing a new version of Zircle soon and github trending will work again.

**Comment by tinchox5** [comment]
Done url API changed
